server:
  port: 8585

trust-store: classpath:ssl/externalProducts/externalProducts.jks
trust-store-password: password

review:
  api: ${reviewAPI:http://localhost:8080/review/}
  auth:
    username: user
    password: password

externalProduct:
  api: ${externalProductAPI:https://localhost:8443/addidas/api/products/}

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:review-service-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  #spring.sql.init.continue-on-error: true