server:
  ssl:
    key-store: classpath:ssl/external-product-service-backend/externalProducts.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: externalProducts
    key-password: password
  port: 8443
