server:
  port: 8080
my:
  prop: defaultProfile
app:
  id: ${app.name:default_app}

---
spring:
  config:
    activate:
      on-profile: qa1
my:
  prop: QA1Profile
---
spring:
  config:
    activate:
      on-profile: qa2
my:
  prop: QA2Profile

